version: '3.8'
services:
  db:
    build: ./backend
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db

